import { useEffect, useMemo, useRef, useState } from 'react'
import { Screen, BigButton, SpeakButton } from '../components/UI'
import MonsterAvatar from '../components/MonsterAvatar'
import { MONSTER_FAMILY, MONSTER_SCENARIOS, NEEDS, REASONS, monsterById } from '../data/monsterFamily'
import { useApp } from '../lib/store'
import { speakSmart as speak } from '../lib/speech'

const GAMES = [
  ['checkin','誰來敲門了？','現在的心情可以不只一種'], ['size','怪獸變大變小','看看心情有多強'],
  ['body','怪獸住在哪？','找找身體裡的感覺'], ['sentence','餵怪獸吃句子','拼出完整的心情句子'],
  ['you','如果是你，誰會來？','每個人的答案都可以不同'], ['book','怪獸圖鑑收集','看看最近誰常來拜訪'],
]

function MonsterGrid({ selected=[], onPick, limit=1 }) {
  return <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-7 gap-3 w-full">{MONSTER_FAMILY.map(m=><button key={m.id} type="button" onClick={()=>onPick(m)} className={`tap card p-2 flex flex-col items-center ${selected.includes(m.id)?'ring-4':''}`} style={{'--tw-ring-color':m.color,borderColor:m.color}}><MonsterAvatar monster={m} size={90} selected={selected.includes(m.id)}/><strong className="text-xl">{m.name}</strong><span>{m.emotion}</span></button>)}</div>
}

export default function MonsterFamily({ go }) {
  const { settings, state, addStars, recordAttempt }=useApp(), [game,setGame]=useState('hub'), [selected,setSelected]=useState([]), [intensity,setIntensity]=useState(2), [zone,setZone]=useState(''), [reason,setReason]=useState(''), [need,setNeed]=useState(''), [scenario,setScenario]=useState(0), [recording,setRecording]=useState(false), recorder=useRef(null)
  useEffect(()=>{if(game==='hub'){const t=setTimeout(()=>speak('沒有壞怪獸，每一種心情都值得被照顧。',settings),250);return()=>clearTimeout(t)}},[game]) // eslint-disable-line react-hooks/exhaustive-deps
  const pick=(m,limit=1)=>setSelected(cur=>cur.includes(m.id)?cur.filter(id=>id!==m.id):[...cur.slice(-(limit-1)),m.id])
  const reward=(mode='monster')=>{for(const id of selected){const m=monsterById(id);recordAttempt({mode,emotionId:m.emotionId,correct:true,tries:1})}addStars(1);speak('謝謝你告訴我。每一種心情都值得被照顧。',settings)}
  const back=()=>{setGame('hub');setSelected([]);setZone('');setReason('');setNeed('');setIntensity(2)}
  const startRecording=async()=>{try{if(recording){recorder.current?.stop();setRecording(false);return}const stream=await navigator.mediaDevices.getUserMedia({audio:true});const r=new MediaRecorder(stream);r.onstop=()=>stream.getTracks().forEach(t=>t.stop());r.start();recorder.current=r;setRecording(true)}catch{setRecording(false);speak('現在不能使用麥克風，也可以跟著句子直接說。',settings)}}
  const counts=useMemo(()=>MONSTER_FAMILY.map(m=>({...m,count:state.attempts.filter(a=>a.mode==='monster'&&a.emotionId===m.emotionId).length})),[state.attempts])
  if(game==='hub')return <Screen title="情緒小怪獸家族" onBack={()=>go('home')}><div className="card p-4 mb-4 flex items-center gap-3"><MonsterAvatar monster={MONSTER_FAMILY[6]} size={90}/><p className="text-xl flex-1">沒有「壞怪獸」。每一隻都是朋友，只是有時候需要被照顧。</p><SpeakButton text="沒有壞怪獸，每一種心情都值得被照顧。"/></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3 flex-1">{GAMES.map(([id,title,desc])=><button key={id} type="button" onClick={()=>setGame(id)} className="tap card p-5 text-left"><strong className="text-2xl block">{title}</strong><span className="text-lg text-inkSoft">{desc}</span></button>)}</div></Screen>
  if(game==='checkin')return <Screen title="誰來敲門了？" onBack={back} backIcon="back" backLabel="回到怪獸家族"><div className="flex-1 flex flex-col items-center justify-center gap-5"><h2 className="text-3xl font-bold">現在來拜訪我的是誰？</h2><p className="text-xl">可以選一隻，也可以選兩隻。</p><MonsterGrid selected={selected} onPick={m=>pick(m,2)} limit={2}/>{selected.length>0&&<BigButton onClick={()=>{reward();back()}}>這就是我現在的心情</BigButton>}</div></Screen>
  if(game==='size'){const m=monsterById(selected[0])||MONSTER_FAMILY[2];return <Screen title="怪獸變大變小" onBack={back} backIcon="back" backLabel="回到怪獸家族"><div className="flex-1 flex flex-col items-center justify-center gap-6"><MonsterGrid selected={[m.id]} onPick={x=>setSelected([x.id])}/><MonsterAvatar monster={m} size={150} intensity={intensity}/><input aria-label="心情強度" type="range" min="1" max="3" value={intensity} onChange={e=>setIntensity(Number(e.target.value))} className="w-full max-w-xl"/><h2 className="text-3xl font-bold">{['有一點','有一些','非常'][intensity-1]}{m.emotion}</h2>{intensity===3&&<p className="text-xl">可以慢慢呼吸、休息一下，或找大人幫忙。</p>}<BigButton onClick={()=>{setSelected([m.id]);reward();back()}}>記下來</BigButton></div></Screen>}
  if(game==='body'){const zones=['頭','胸口','肚子','手和拳頭','腿和腳'];return <Screen title="怪獸住在哪？" onBack={back} backIcon="back" backLabel="回到怪獸家族"><div className="flex-1 flex flex-col items-center justify-center gap-5"><MonsterGrid selected={selected} onPick={m=>pick(m)}/><div className="card p-5 w-full max-w-2xl text-center"><div className="mx-auto w-28 h-28 rounded-full border-4 border-ink/50"/><div className="mx-auto w-48 h-64 rounded-[45%] border-4 border-ink/50 flex flex-col justify-around p-3">{zones.map(z=><button key={z} onClick={()=>setZone(z)} className={`tap rounded-xl p-2 text-xl ${zone===z?'bg-yellow-200 ring-4 ring-yellow-400':'bg-paper'}`}>{z}</button>)}</div></div>{selected.length>0&&zone&&<BigButton onClick={()=>{reward();back()}}>{monsterById(selected[0]).name}住在{zone}</BigButton>}</div></Screen>}
  if(game==='sentence'){const m=monsterById(selected[0]);const sentence=m&&reason&&need?`我覺得${m.emotion}，因為${reason}，我需要${need}。`:'';return <Screen title="餵怪獸吃句子" onBack={back} backIcon="back" backLabel="回到怪獸家族"><div className="flex-1 flex flex-col items-center justify-center gap-4"><MonsterGrid selected={selected} onPick={x=>pick(x)}/><div className="grid md:grid-cols-2 gap-3 w-full"><select aria-label="原因" value={reason} onChange={e=>setReason(e.target.value)} className="card p-4 text-xl"><option value="">因為……</option>{REASONS.map(x=><option key={x}>{x}</option>)}</select><select aria-label="需要" value={need} onChange={e=>setNeed(e.target.value)} className="card p-4 text-xl"><option value="">我需要……</option>{NEEDS.map(x=><option key={x}>{x}</option>)}</select></div>{sentence&&<><div className="card p-5 text-2xl font-bold flex items-center gap-3"><span>{sentence}</span><SpeakButton text={sentence}/></div><button type="button" onClick={startRecording} className={`tap card p-4 text-xl ${recording?'bg-red-100':''}`}>{recording?'停止錄音':'可選：錄下我說的句子'}</button><BigButton onClick={()=>{reward();back()}}>餵飽怪獸</BigButton></>}</div></Screen>}
  if(game==='you'){const [text,ids]=MONSTER_SCENARIOS[scenario%MONSTER_SCENARIOS.length];return <Screen title="如果是你，誰會來？" onBack={back} backIcon="back" backLabel="回到怪獸家族"><div className="flex-1 flex flex-col items-center justify-center gap-5"><div className="card p-6 text-3xl max-w-3xl">{text}</div><p className="text-xl">沒有標準答案，選最像你的怪獸。</p><MonsterGrid selected={selected} onPick={m=>pick(m,2)}/>{selected.length>0&&<BigButton onClick={()=>{reward();setSelected([]);setScenario(n=>n+1)}}>這是我的版本 ▶</BigButton>}<p className="text-inkSoft">提示：也可能是 {ids.map(monsterById).map(m=>m.name).join('、')}，每個人都不一樣。</p></div></Screen>}
  return <Screen title="怪獸圖鑑收集" onBack={back} backIcon="back" backLabel="回到怪獸家族"><p className="text-center text-xl mb-4">每次說出心情，就會留下拜訪紀錄。</p><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{counts.map(m=><div key={m.id} className="card p-3 flex flex-col items-center"><MonsterAvatar monster={m} size={105}/><strong className="text-2xl">{m.name}</strong><span>{m.emotion}</span><span className="mt-2 text-lg">最近出現 {m.count} 次</span></div>)}</div></Screen>
}
